# Site settings
title: Davy Karlsson
email: dk222gw@lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Min egengjorda bloggsida för uppgift 1 i 1dv022 - Klientbaserad Webbprogrammering.
  Gjord utav dk222gw - Davy Karlsson.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
image: "https://scontent-arn2-1.cdninstagram.com/t51.2885-19/s320x320/13556729_1063424913752591_1991802169_a.jpg"
twitter_username: DavyJonesK
github_username: Davy1993

# Build settings
markdown: kramdown

#Permalink structure
permalink: /blog/:year/:month/:day/:title

# Disqus post comments
disqus_shortname: davyk
